# Generated by Django 5.0.7 on 2026-01-08 22:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True, verbose_name='Назва')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата створення')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата оновлення')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активний')),
            ],
            options={
                'verbose_name': 'Канал',
                'verbose_name_plural': 'Канали',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Variable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True, verbose_name='Назва')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата створення')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата оновлення')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активний')),
            ],
            options={
                'verbose_name': 'Змінна',
                'verbose_name_plural': 'Змінні',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='NotificationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата створення')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата оновлення')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активний')),
                ('title', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Назва типу')),
                ('is_custom', models.BooleanField(default=True, verbose_name='Кастомний тип')),
                ('channels', models.ManyToManyField(blank=True, related_name='notification_types', to='notifications.channel', verbose_name='Канали')),
                ('variables', models.ManyToManyField(blank=True, related_name='notification_types', to='notifications.variable', verbose_name='Змінні')),
            ],
            options={
                'verbose_name': 'Тип нотифікації',
                'verbose_name_plural': 'Типи нотифікацій',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True, verbose_name='Назва')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата створення')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата оновлення')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активний')),
                ('html', models.TextField(verbose_name='HTML шаблон')),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='templates', to='notifications.channel', verbose_name='Канал')),
                ('notification_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='templates', to='notifications.notificationtype', verbose_name='Тип нотифікації')),
            ],
            options={
                'verbose_name': 'Шаблон нотифікації',
                'verbose_name_plural': 'Шаблони нотифікацій',
                'ordering': ['notification_type', 'channel'],
            },
        ),
    ]
