# Generated by Django 5.0.7 on 2026-01-08 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='allowed_tags',
            field=models.JSONField(default=list, verbose_name='Дозволені HTML теги'),
        ),
        migrations.AddField(
            model_name='notificationtemplate',
            name='name',
            field=models.CharField(blank=True, help_text='Назва шаблону', max_length=100, null=True, verbose_name='Назва'),
        ),
        migrations.AlterField(
            model_name='notificationtemplate',
            name='html',
            field=models.TextField(help_text='HTML шаблон', verbose_name='HTML шаблон'),
        ),
        migrations.AlterField(
            model_name='notificationtemplate',
            name='title',
            field=models.CharField(blank=True, help_text='Заголовок', max_length=200, verbose_name='Заголовок'),
        ),
    ]
