# Generated by Django 5.0.7 on 2026-01-12 14:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='APILog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(max_length=10, verbose_name='HTTP Method')),
                ('path', models.CharField(max_length=500, verbose_name='Path')),
                ('query_params', models.JSONField(blank=True, default=dict, verbose_name='Query Parameters')),
                ('request_body', models.TextField(blank=True, null=True, verbose_name='Request Body')),
                ('response_status', models.IntegerField(verbose_name='Response Status Code')),
                ('response_body', models.TextField(blank=True, null=True, verbose_name='Response Body')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Address')),
                ('user_agent', models.CharField(blank=True, max_length=500, null=True, verbose_name='User Agent')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('duration_ms', models.FloatField(blank=True, null=True, verbose_name='Duration (ms)')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='Error Message')),
                ('error_traceback', models.TextField(blank=True, null=True, verbose_name='Error Traceback')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'API Log',
                'verbose_name_plural': 'API Logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='api_logging_created_40e0c7_idx'), models.Index(fields=['response_status'], name='api_logging_respons_fe4698_idx'), models.Index(fields=['method', 'path'], name='api_logging_method_508297_idx')],
            },
        ),
    ]
